# Generated by Django 4.2.5 on 2023-12-12 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_of_operation', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=30, null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
