# Generated by Django 4.2.5 on 2023-12-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companysuggestionmodel'),
        ('company', '0003_rate'),
    ]

    operations = [
    ]
