# Generated by Django 4.2.5 on 2023-12-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_rate_company_alter_rate_score_alter_rate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysuggestionmodel',
            name='status',
            field=models.CharField(choices=[('RE', 'Recusado'), ('NV', 'Não verificado'), ('AP', 'Aprovado')], default='NV', max_length=20),
        ),
    ]
