# Generated by Django 4.2.5 on 2023-09-17 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'verbose_name_plural': 'Report categories'},
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='formatted_name',
            field=models.CharField(default='Categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
