# Generated by Django 4.2.5 on 2023-09-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reportcategory',
            name='reports',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infos.reportcategory'),
        ),
    ]
