# Generated by Django 4.2.5 on 2023-12-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options'),
        ('infos', '0002_alter_report_company_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source', models.URLField()),
                ('start_year', models.PositiveSmallIntegerField()),
                ('resolution_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawsuits', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
