# Generated by Django 4.2.5 on 2023-12-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_alter_report_user'),
        ('infos', '0004_report_status'),
    ]

    operations = [
    ]
