# Generated by Django 4.2.5 on 2023-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infos", "0006_report_date_report_gravity"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
