# Generated by Django 4.2.5 on 2023-12-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_alter_report_user'),
        ('infos', '0007_report_feedback'),
    ]

    operations = [
    ]
