# Generated by Django 4.2.5 on 2023-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infos", "0008_merge_0007_alter_report_user_0007_report_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(default="", upload_to="news_banners"),
            preserve_default=False,
        ),
    ]
